services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin123"
      POSTGRES_DB: "pagamento"
    ports:
      - "5432:5432"
      
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "teste"  # Alterado para "admin" - usuário root padrão
      MONGO_INITDB_ROOT_PASSWORD: "admin123"
      MONGO_INITDB_DATABASE: "pedidos"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: ["--auth"]

volumes:
  mongodb_data:
