
apiVersion: v1
kind: ServiceAccount
metadata:
  name: processor-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::783545975704:role/processor-irsa-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  labels:
    app: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      serviceAccountName: processor-sa
      containers:
      - name: processor
        image: 783545975704.dkr.ecr.us-east-1.amazonaws.com/processor:latest
        ports:
        - containerPort: 8080
        env:
        - name: CORE_SERVICE_URL
          value: "http://core-api-service.default.svc.cluster.local"
        - name: SQS_PROCESS
          value: "https://sqs.us-east-1.amazonaws.com/783545975704/video-processing-queue"
        - name: S3_BUCKET_NAME
          value: "fiapfase5-user-video-uploads"
        - name: S3_DOWNLOAD_BUCKET
          value: "fiapfase5-processed-videos"
        - name: EMAIL_FROM
          value: "macacolaranja4@gmail.com"
        - name: EMAIL_PASS
          value: "muad srjx cswo siqe"
---
apiVersion: v1
kind: Service
metadata:
  name: processor-service
spec:
  selector:
    app: processor
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP